### ISSUE TITLE
Doesn't seem to work when IRequest is a record struct

### ISSUE THREAD

**Issue by jameswilliamknight** [kzryzstof/mediatr-plugin#24]
I can't see the lightbulb after I click on the type name:

```csharp
//                            VVVVVVVVV
public readonly record struct MyRequest(string input) : IRequest<CommandResult>;
```

```csharp
public class MyRequestHandler : IRequestHandler<MyRequest, CommandResult>
{
    private readonly ILogger<MyRequestHandler> _logger;

    public MyRequestHandler (ILogger<MyRequestHandler> logger)
    {
        _logger = logger;
    }

    public async Task<CommandResult> Handle(
        MyRequest command,
        CancellationToken cancellationToken)
    {
        return await Task.FromResult<CommandResult>(new(CommandResultCode.Ok));
    }
}
```

I haven't read the code, my guess is that class types are only supported so far

**Comment by kzryzstof** [comment]
I just tried this on different setup. 

First, on Windows running Visual Studio 2022:

![devenv_HptTU4rbUo](https://user-images.githubusercontent.com/38137839/158064016-ef882ebd-86d0-4323-8762-df34e23505b4.gif)

Then, on Windows running Rider 2021.3.3:

![rider64_yiroc8jhbg](https://user-images.githubusercontent.com/38137839/158064196-b7911dfe-c08d-433a-ad0f-f45b8c5156d3.gif)

Is there anything different in your setup that I am most likely missing?

**Comment by jameswilliamknight** [comment]
My guess was wrong! The context menu is appearing for me now, I'm not sure what prevented it before.

Thank you for looking into this
