### ISSUE TITLE
Shortcut key 

### ISSUE THREAD

**Issue by beakersoft** [kzryzstof/mediatr-plugin#34]
Is there anyway to use a shortcut key to goto the handler instead of having to use the mouse to go into the menu and pick the option, i think that would be really useful

**Comment by kzryzstof** [comment]
Hi @beakersoft!

That is a very good suggestion. Considering how challenging it is to develop a ReSharper / Rider extension, do you have a preference? Are you a ReSharper person or a Rider person?

**Comment by beakersoft** [comment]
Hey @kzryzstof, so I just use ReSharper so that would be my personal preference. I've never worked with this extension eco-system before, if i had time i'd probably just look at it myself and fire a PR over but I'm kinda busy at the moment.

**Comment by kzryzstof** [comment]
@beakersoft Good :) I will try with ReSharper then; I had done something for Rider..

**Comment by beakersoft** [comment]
@kzryzstof that would be amazing, let me know if you want me to test it out

**Comment by kzryzstof** [comment]
@beakersoft The change has been made so that a keyboard shortcut can be assigned.

Go to `Tools `> `Options `> `Environment `> `Keyboard `and look for `GoToHandlrAction` to assign the preferred keyboard shortcut.

**Comment by beakersoft** [comment]
@kzryzstof cool ill give it a try
