### ISSUE TITLE
Plugin navigates to wrong handler

### ISSUE THREAD

**Issue by BggClr** [kzryzstof/mediatr-plugin#40]
If we have project structure as below
![image](https://user-images.githubusercontent.com/7804670/190996126-0313c765-882a-4f5c-ad02-bc4d07c21111.png)

Plugin navigates to the random CommandHandler, but expect to navigate to correct one

Environment: 
Plugin version: Version 22.6.1101
IDE: jetBrains Rider 2022.2.3

**Comment by kzryzstof** [comment]
@BggClr Are both `CommandHandler`s implementing an `IRequestHandler<Command>` but both they are referencing `Command`s in different namespaces? Would it be possible to just show the declarations of `Command`s and `CommandHandler`s without the rest?

**Comment by kzryzstof** [comment]
It is supposed to be fixed in 22.09.2005. It should be available soon; waiting for Jetbrains' approval.

**Comment by kzryzstof** [comment]
The update is now available :)

**Comment by BggClr** [comment]
Many thanks for such quick fix
