### ISSUE TITLE
It is not possible go to handler if it is not direct IRequestHandler implementation

### ISSUE THREAD

**Issue by alewmt** [kzryzstof/mediatr-plugin#46]
Hi! It would be great if it could go to handlers that implement the `IRequestHandler` interface not directly, but through intermediate interfaces like this:
```
public interface ICommandHandler<in TCommand> : IRequestHandler<TCommand>
{
}

public class SomeCommandHandler : ICommandHandler<SomeCommand>
{
}
```

**Comment by kzryzstof** [comment]
@alewmt I have done a couple tests and it seems to already work. Are you certain your example represents exactly your use case?

**Comment by kzryzstof** [comment]
It should be working in version `22.11.2503` that I expect to be available on Monday once it passes Jetbrains' validation.
