### ISSUE TITLE
[Bug] Create HandlR action on class instance

### ISSUE THREAD

**Issue by rolandcheck** [kzryzstof/mediatr-plugin#55]
`Create HandlR` action does not work as intended when caret is on instance rather than class definition.
It takes Controller name (request object instantiated in controller action) as generic argument for `IRequestHandler`
Dont actually know should this action be on object constructor call or not as well as where handler should be rendered in this case

**Comment by kzryzstof** [comment]
Thank you for reporting the issue :)

It will be fixed in version `24.06.1402`.
