### ISSUE TITLE
[Bug] "Go to Handlr" does not work if handler declared inside class 

### ISSUE THREAD

**Issue by rolandcheck** [kzryzstof/mediatr-plugin#57]
Noticed that if handler declared as nested class navigation does not work
My common structure is when my handler class is wrapped in command, so me personally it does not bother
I think worth look into this as well when it will come to reworking searching & navigation

```c#
// one file
record Command: IRequest;

// other file
class Wrapper {
    class CommandHandler : IRequestHandler<Command, Unit>
    {
        public Task<Unit> Handle(Command request, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }
    }
}
```
If I remove Wapper class navigation works as intended

**Comment by kzryzstof** [comment]
Issue should be fixed in version `24.06.1201`.
